Applied Omen Wild's patch for advanced scheduling.

diff --git a/debian/boinc-client.init b/debian/boinc-client.init
--- a/debian/boinc-client.init
+++ b/debian/boinc-client.init
@@ -32,7 +32,7 @@ fi
 test "$ENABLED" != "0" || exit 0
 
 if [ ! -x "$BOINC_CLIENT" ]; then
-  log_failure_msg "BOINC client '$BOINC_CLIENT' does not exist or is not " \
+  log_failure_msg "BOINC client '$BOINC_CLIENT' does not exist or is not" \
     "executable."
   exit 5
 fi
@@ -43,7 +43,7 @@ if [ ! -d "$BOINC_DIR" ]; then
 fi
 
 if [ -z "$BOINC_USER" ]; then
-  log_failure_msg "BOINC_USER variable is empty. Set it to a user to run " \
+  log_failure_msg "BOINC_USER variable is empty. Set it to a user to run" \
     "the BOINC core client."
   exit 6
 fi
@@ -73,8 +73,8 @@ start()
     log_progress_msg "already running"
   else
     start-stop-daemon --start --quiet --background --pidfile $PIDFILE \
-      --make-pidfile --user $BOINC_USER --chuid $BOINC_USER --chdir $BOINC_DIR \
-      --exec $BOINC_CLIENT -- $BOINC_OPTS
+      --make-pidfile --user $BOINC_USER --chuid $BOINC_USER \
+      --chdir $BOINC_DIR --exec $BOINC_CLIENT -- $BOINC_OPTS
   fi
   log_end_msg 0
 }
@@ -94,11 +94,60 @@ stop()
   log_end_msg 0
 }
 
+schedule()
+{
+  log_begin_msg "Setting up scheduling for $DESC and children:"
+
+  if ! is_running; then
+    log_progress_msg "not running"
+    log_end_msg 0
+  else
+    if [ -z $pid ]; then
+      log_failure_msg "unable to find pid to do scheduling."
+      return 1
+    fi
+
+    if [ ! -x "`which ionice 2>/dev/null`" ]; then
+      log_progress_msg "no ionice in the path,"
+    else
+      ionice -n 4 -c 3 -p $pid
+      log_progress_msg "ioniced,"
+    fi
+
+    if [ ! -x "`which schedtool 2>/dev/null`" ]; then
+      log_progress_msg "no schedtool in the path"
+    else
+      max=5
+      while [ "x$children" = "x" ] && [ $max -ge 0 ]; do
+        children=$(ps --ppid $pid -opid= | tr '\n' ' ' || true)
+        [ "x$children" = "x" ] && sleep 1
+        max=$(expr $max - 1)
+      done
+
+      if [ "x$children" != "x" ]; then
+        ( schedtool -n 19 -D $pid $children >/dev/null && log_progress_msg "idleprio") || \
+         (schedtool -n 19 -B $pid $children >/dev/null && log_progress_msg "batch" ) || \
+         (schedtool -n 19    $pid $children            && log_progress_msg "only niced")
+      else
+        log_progress_msg "unable to find any children"
+      fi
+    fi
+
+    log_end_msg 0
+  fi
+}
+
 status()
 {
   STATUS="Status of $DESC:"
   if is_running; then
     log_success_msg "$STATUS running."
+    if [ -x "`which schedtool 2>/dev/null`" ]; then
+      log_success_msg "Scheduling of $DESC:"
+      schedtool $pid
+      log_success_msg "Scheduling of $DESC's children:"
+      schedtool $(ps --ppid $pid -o pid=)
+    fi
   else
     log_success_msg "$STATUS stopped."
   fi
@@ -123,8 +172,12 @@ case "$1" in
     status
     ;;
 
+  schedule)
+    schedule
+    ;;
+
   *)
-    log_success_msg "Usage: $0 {start|stop|restart|force-reload|status}" >&2
+    log_success_msg "Usage: $0 {start|stop|restart|force-reload|status|schedule}" >&2
     exit 1
     ;;
 esac
